export const MARKET_TICKERS = [
  { symbol: "NIFTY", price: "24,812.45", change: "+0.82%", dir: "up" },
  { symbol: "BANKNIFTY", price: "52,340.10", change: "-0.43%", dir: "down" },
  { symbol: "BTC/USD", price: "$72,450.31", change: "+1.24%", dir: "up" },
  { symbol: "ETH/USD", price: "$3,892.15", change: "+0.67%", dir: "up" },
  { symbol: "RELIANCE", price: "₹2,981.60", change: "+1.12%", dir: "up" },
  { symbol: "TCS", price: "₹3,872.25", change: "-0.38%", dir: "down" },
  { symbol: "INFY", price: "₹1,640.80", change: "+0.55%", dir: "up" },
  { symbol: "HDFCBANK", price: "₹1,712.45", change: "-0.21%", dir: "down" },
];

export const SYSTEM_STATS = {
  latencyBase: 12,
  node: "IC_MAINNET",
  engine: "V.4.0-XENON",
  version: "v4.0-XENON",
};

export const ACTION_CARDS = [
  {
    id: "predictions",
    title: "CHECK_PREDICTIONS",
    description: "Generate F&O signals for NIFTY, BTC & more",
    icon: "Brain",
    route: "/predictions",
    color: "green",
    stat: "WIN_RATE: 72.1%",
  },
  {
    id: "indian-market",
    title: "INDIAN_STOCKS",
    description: "Live NSE/BSE prices and BUY/SELL signals",
    icon: "TrendingUp",
    route: "/indian-market",
    color: "cyan",
    stat: "55 SYMBOLS_LIVE",
  },
  {
    id: "risk",
    title: "POSITION_SIZE",
    description: "Calculate your optimal trade size",
    icon: "Calculator",
    route: "/risk",
    color: "amber",
    stat: "RISK: MANAGED",
  },
  {
    id: "arbitrage",
    title: "ARBITRAGE_SCAN",
    description: "Detect live sports & financial arbitrage opportunities",
    icon: "Radar",
    route: "/arbitrage",
    color: "green",
    stat: "OPPS: 3_LIVE",
  },
  {
    id: "dashboard",
    title: "DASHBOARD",
    description: "Full live session P&L and system status",
    icon: "BarChart2",
    route: "/dashboard",
    color: "cyan",
    stat: "P&L: +₹12,340",
  },
] as const;

export const ONBOARDING_SLIDES = [
  {
    phase: "PHASE_01",
    title: "ARBITRAGE_ENGINE",
    subtitle: "QUANTUM_ARBITRAGE_DETECTION_SYSTEM",
    description:
      "Aegis Quantum scans thousands of data streams simultaneously to detect pricing inefficiencies across exchanges, sports books, and financial instruments in real-time.",
    stats: [
      { label: "DETECTION_RATE", value: "99.98%", color: "green" },
      { label: "CORE_TEMP", value: "42.1°C", color: "cyan" },
      { label: "SLIPPAGE_PROT", value: "ACTIVE", color: "green" },
      { label: "SCAN_NODES", value: "247", color: "cyan" },
    ],
    art: [
      "╔══════════════════════╗",
      "║  ARBITRAGE_MATRIX    ║",
      "║  ▓▓▓▒▒░░▓▓▓▒▒░░▓▓▓  ║",
      "║  NSE ──►── BSE       ║",
      "║    ↘         ↗       ║",
      "║   CRYPTO_BRIDGE      ║",
      "║    ↗         ↘       ║",
      "║  FOREX ──►── BONDS   ║",
      "║  ▓▓▓▒▒░░▓▓▓▒▒░░▓▓▓  ║",
      "║  PROFIT_LOCKED: ✓    ║",
      "╚══════════════════════╝",
    ],
  },
  {
    phase: "PHASE_02",
    title: "INDIAN_F&O_BASICS",
    subtitle: "NSE_BSE_DERIVATIVES_MODULE",
    description:
      "Master Futures & Options on India's largest exchanges. Trade NIFTY 50 and BANKNIFTY contracts with institutional-grade signal precision tailored for the Indian market.",
    stats: [
      { label: "NSE_SYMBOLS", value: "55+", color: "green" },
      { label: "F&O_LOT_NIFTY", value: "50", color: "cyan" },
      { label: "EXPIRY_CYCLE", value: "WEEKLY", color: "amber" },
      { label: "MARGIN_REQ", value: "~₹1.2L", color: "cyan" },
    ],
    art: [
      "╔══════════════════════╗",
      "║  NSE_F&O_TERMINAL    ║",
      "║                      ║",
      "║  NIFTY  24,812 ▲     ║",
      "║  CALL  [BUY] ████    ║",
      "║  PUT   [SELL] ▒▒▒    ║",
      "║                      ║",
      "║  BANKNIFTY 52,340    ║",
      "║  SIGNAL: BUY_CALL    ║",
      "║  CONF: [████░░] 73%  ║",
      "╚══════════════════════╝",
    ],
  },
  {
    phase: "PHASE_03",
    title: "QUANTUM_PREDICTIONS",
    subtitle: "CANDLE_LOCKED_SIGNAL_ENGINE",
    description:
      "Signals are generated using deterministic quantum algorithms. Same asset, same timeframe, same candle = same signal. No randomness. No fluctuation. Candle-locked precision.",
    stats: [
      { label: "SIGNAL_LOCK", value: "CANDLE", color: "green" },
      { label: "CONFIDENCE_IDX", value: "73.4%", color: "cyan" },
      { label: "TIMEFRAMES", value: "7_ACTIVE", color: "green" },
      { label: "ALGO_VERSION", value: "QNT_4.0", color: "amber" },
    ],
    art: [
      "╔══════════════════════╗",
      "║  SIGNAL_MATRIX       ║",
      "║                      ║",
      "║  15M  ► BUY_CALL ✓   ║",
      "║  30M  ► BUY_CALL ✓   ║",
      "║  1H   ► HOLD     ◌   ║",
      "║  4H   ► BUY_CALL ✓   ║",
      "║  1D   ► BUY_CALL ✓   ║",
      "║                      ║",
      "║  CONSENSUS: 80% BUY  ║",
      "╚══════════════════════╝",
    ],
  },
  {
    phase: "PHASE_04",
    title: "RISK_MANAGEMENT",
    subtitle: "GUARDIAN_KILL_SWITCH_PROTOCOL",
    description:
      "Never blow your account. Aegis Quantum's Risk Guardian calculates optimal position sizes, monitors margin usage, and triggers kill switches when drawdown limits are breached.",
    stats: [
      { label: "KILL_SWITCH", value: "ARMED", color: "red" },
      { label: "SAFETY_SCORE", value: "94/100", color: "green" },
      { label: "MAX_DRAWDOWN", value: "2%", color: "amber" },
      { label: "POS_SIZING", value: "AUTO", color: "cyan" },
    ],
    art: [
      "╔══════════════════════╗",
      "║  RISK_GUARDIAN       ║",
      "║                      ║",
      "║  PORTFOLIO: ████░    ║",
      "║  RISK_GAUGE: [LOW]   ║",
      "║                      ║",
      "║  ⚠ KILL_SWITCH:      ║",
      "║    DRAWDOWN > 2%     ║",
      "║    ► AUTO_STOP ✓     ║",
      "║                      ║",
      "║  SAFETY_SCORE: 94    ║",
      "╚══════════════════════╝",
    ],
  },
  {
    phase: "PHASE_05",
    title: "SYSTEM_INITIALIZATION",
    subtitle: "AEGIS_QUANTUM_READY_TO_DEPLOY",
    description:
      "All systems nominal. Aegis Quantum v4.0-XENON is fully initialized and ready to execute. Your quantum trading terminal awaits operator commands.",
    stats: [
      { label: "SYSTEM_STATUS", value: "ONLINE", color: "green" },
      { label: "ENGINE", value: "V4.0-XENON", color: "cyan" },
      { label: "NODE", value: "IC_MAINNET", color: "green" },
      { label: "OPERATOR", value: "SOVEREIGN", color: "cyan" },
    ],
    art: [
      "╔══════════════════════╗",
      "║  ██████████████████  ║",
      "║  █                █  ║",
      "║  █  AEGIS QUANTUM  █  ║",
      "║  █  v4.0 - XENON   █  ║",
      "║  █                █  ║",
      "║  ██████████████████  ║",
      "║                      ║",
      "║  ALL_SYSTEMS: GO ✓   ║",
      "║  INITIALIZE? [YES]   ║",
      "╚══════════════════════╝",
    ],
  },
] as const;
