/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ATR { 'value' : number }
export type AssetClass = string;
export type AssetId = string;
export interface BacktestConfig {
  'model' : QuantModel,
  'pairsAssetId' : [] | [AssetId],
  'walkForwardSplit' : number,
  'endDate' : Timestamp,
  'timeframe' : Timeframe,
  'assetId' : AssetId,
  'strategyParams' : QuantSettings,
  'includeRegimeBreakdown' : boolean,
  'runLabel' : [] | [string],
  'initialCapital' : number,
  'assetClass' : AssetClass,
  'startDate' : Timestamp,
}
export type BacktestDirection = { 'Short' : null } |
  { 'Long' : null };
export interface BacktestMetrics {
  'avgReturn' : number,
  'sharpeRatio' : number,
  'winRate' : number,
  'maxDrawdown' : number,
  'lookbackCandles' : bigint,
}
export interface BacktestMetricsExtended {
  'model' : QuantModel,
  'calibrationTable' : [] | [CalibrationTable],
  'numberOfTrades' : bigint,
  'outOfSampleWinRate' : [] | [number],
  'averageLoss' : number,
  'sharpeRatio' : number,
  'inSampleWinRate' : [] | [number],
  'averageWin' : number,
  'sortinoRatio' : number,
  'totalReturn' : number,
  'regimeBreakdown' : [] | [Array<RegimePerformance>],
  'winRate' : number,
  'maxDrawdown' : number,
  'profitFactor' : number,
}
export interface BacktestResult {
  'metrics' : BacktestMetricsExtended,
  'trades' : Array<BacktestTrade>,
  'equityCurve' : Array<EquityPoint>,
  'config' : BacktestConfig,
  'runAt' : Timestamp,
}
export type BacktestStatus = { 'Failed' : null } |
  { 'Partial' : null } |
  { 'Completed' : null };
export interface BacktestSummary {
  'id' : bigint,
  'status' : BacktestStatus,
  'metrics' : BacktestMetricsExtended,
  'tradeCount' : bigint,
  'runLabel' : [] | [string],
  'config' : BacktestConfig,
  'runAt' : Timestamp,
}
export interface BacktestTrade {
  'pnl' : number,
  'direction' : BacktestDirection,
  'returnPercent' : number,
  'entryTimestamp' : Timestamp,
  'holdingPeriod' : bigint,
  'exitTimestamp' : Timestamp,
  'entryPrice' : number,
  'exitPrice' : number,
}
export interface BollingerBands {
  'percentB' : number,
  'middle' : number,
  'lower' : number,
  'upper' : number,
}
export interface CCI {
  'overbought' : boolean,
  'value' : number,
  'oversold' : boolean,
}
export interface CalibratedConfidence {
  'warning' : string,
  'isCalibrated' : boolean,
  'rawConfidence' : number,
  'bucket' : CalibrationBucket,
  'calibratedConfidence' : number,
}
export interface CalibrationBucket {
  'realizedWinRate' : number,
  'reliabilityGrade' : string,
  'reliabilityFactor' : number,
  'sampleCount' : bigint,
  'maxConfidence' : number,
  'minConfidence' : number,
}
export interface CalibrationTable {
  'totalSamples' : bigint,
  'lastUpdated' : Timestamp,
  'disclaimer' : string,
  'buckets' : Array<CalibrationBucket>,
}
export interface ConfluenceResult {
  'primaryTimeframe' : Timeframe,
  'votes' : Array<TimeframeVote>,
  'finalBias' : string,
  'weightedScore' : number,
  'confluenceScore' : bigint,
}
export interface ConfluenceWeights {
  'd1' : bigint,
  'h1' : bigint,
  'h4' : bigint,
  'm15' : bigint,
  'lowerTimeframe' : bigint,
  'higherTimeframe' : bigint,
  'selectedTimeframe' : bigint,
}
export type Direction = { 'Short' : null } |
  { 'Long' : null };
export interface EquityPoint {
  'drawdown' : number,
  'timestamp' : Timestamp,
  'equity' : number,
}
export interface GradeDistribution {
  'gradeA' : bigint,
  'gradeB' : bigint,
  'gradeC' : bigint,
  'gradeD' : bigint,
  'gradeF' : bigint,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type IndicatorSet = { 'Minimal' : null } |
  { 'Full' : null };
export interface KeyLevel { 'kind' : string, 'name' : string, 'price' : number }
export interface MACD {
  'histogram' : number,
  'macdLine' : number,
  'signalLine' : number,
}
export type MarketRegime = { 'trendingUp' : null } |
  { 'trendingDown' : null } |
  { 'volatile' : null } |
  { 'ranging' : null };
export type Mode = { 'Beginner' : null } |
  { 'Advanced' : null } |
  { 'PowerUser' : null } |
  { 'Intermediate' : null } |
  { 'Optional' : null };
export interface ModelComparison {
  'timeframe' : Timeframe,
  'assetId' : AssetId,
  'results' : Array<ModelComparisonEntry>,
  'dateRange' : string,
}
export interface ModelComparisonEntry {
  'totalTrades' : bigint,
  'model' : QuantModel,
  'sharpe' : number,
  'outOfSampleWinRate' : [] | [number],
  'winRate' : number,
  'maxDrawdown' : number,
  'profitFactor' : number,
}
export type ModelDirection = { 'long' : null } |
  { 'short' : null } |
  { 'neutral' : null };
export interface ModelSignal {
  'model' : QuantModel,
  'direction' : ModelDirection,
  'metrics' : string,
  'takeProfit' : number,
  'reasoning' : string,
  'stopLoss' : number,
  'entryPrice' : number,
  'confidence' : number,
}
export type NodeClass = { 'HVN' : null } |
  { 'LVN' : null } |
  { 'POC' : null } |
  { 'Other' : null };
export interface OHLC {
  'low' : number,
  'high' : number,
  'close' : number,
  'open' : number,
  'volume' : number,
  'timestamp' : bigint,
}
export type Outcome = { 'Open' : null } |
  { 'HitTarget' : null } |
  { 'HitStop' : null };
export interface OutcomeBreakdown {
  'open' : bigint,
  'hitTarget' : bigint,
  'hitStop' : bigint,
}
export interface PracticeStats {
  'avgRiskReward' : number,
  'totalTrades' : bigint,
  'wins' : bigint,
  'losses' : bigint,
  'totalPnl' : number,
  'winRate' : number,
  'avgPnl' : number,
}
export interface PracticeTrade {
  'id' : bigint,
  'pnl' : [] | [number],
  'status' : TradeStatus,
  'direction' : Direction,
  'assetId' : string,
  'createdAt' : bigint,
  'targetPrice' : number,
  'scope' : string,
  'stopLoss' : number,
  'timestamp' : bigint,
  'entryPrice' : number,
  'assetClass' : string,
  'resolvedAt' : [] | [bigint],
}
export interface PredictionFilter {
  'endDate' : [] | [bigint],
  'timeframe' : [] | [Timeframe],
  'assetId' : [] | [string],
  'grade' : [] | [SignalGrade],
  'outcome' : [] | [Outcome],
  'signalType' : [] | [SignalType],
  'startDate' : [] | [bigint],
}
export interface PredictionRecord {
  'id' : bigint,
  'pnl' : [] | [number],
  'timeframe' : Timeframe,
  'assetId' : string,
  'targetPrice' : number,
  'grade' : SignalGrade,
  'stopLoss' : number,
  'timestamp' : bigint,
  'entryPrice' : number,
  'signal' : SignalType,
  'confidence' : bigint,
  'outcome' : [] | [Outcome],
  'assetClass' : string,
  'resolvedAt' : [] | [bigint],
}
export interface PredictionStats {
  'avgRiskReward' : number,
  'bestTrade' : number,
  'worstTrade' : number,
  'gradeDistribution' : GradeDistribution,
  'sharpeLikeRatio' : number,
  'totalPredictions' : bigint,
  'outcomeBreakdown' : OutcomeBreakdown,
  'winRate' : number,
  'resolvedCount' : bigint,
  'avgPnl' : number,
}
export type PricePosition = { 'InVA' : null } |
  { 'BelowVA' : null } |
  { 'AboveVA' : null };
export type QuantModel = { 'auto' : null } |
  { 'momentum' : null } |
  { 'meanReversion' : null } |
  { 'pairs' : null };
export interface QuantSettings {
  'maxRiskPercent' : number,
  'useRegimeFilter' : boolean,
  'useVWAP' : boolean,
  'indicatorSet' : IndicatorSet,
  'accountSize' : number,
  'minConfidence' : bigint,
  'confluenceWeights' : ConfluenceWeights,
  'backtestLookback' : bigint,
}
export interface RSI {
  'overbought' : boolean,
  'value' : number,
  'oversold' : boolean,
}
export interface RegimeAssessment {
  'adx' : number,
  'regime' : MarketRegime,
  'plusDI' : number,
  'minusDI' : number,
  'reasoning' : string,
  'atrPercentile' : number,
  'priceVsEma200' : { 'above' : null } |
    { 'near' : null } |
    { 'below' : null },
  'confidence' : number,
}
export interface RegimeHistoryEntry {
  'regime' : MarketRegime,
  'timestamp' : Timestamp,
}
export interface RegimePerformance {
  'regime' : MarketRegime,
  'tradeCount' : bigint,
  'winRate' : number,
}
export interface RegimeStrategyWeights {
  'sizeMultiplier' : number,
  'momentum' : number,
  'meanReversion' : number,
  'pairs' : number,
}
export type Result = { 'Ok' : Array<OHLC> } |
  { 'Err' : string };
export type Result_1 = { 'Ok' : number } |
  { 'Err' : string };
export type SignalGrade = { 'A' : null } |
  { 'B' : null } |
  { 'C' : null } |
  { 'D' : null } |
  { 'F' : null };
export interface SignalReportCard {
  'regime' : VolatilityRegime,
  'volumeProfile' : [] | [VolumeProfile],
  'model' : QuantModel,
  'backtest' : BacktestMetrics,
  'expectedValue' : number,
  'keyLevels' : Array<KeyLevel>,
  'bias' : string,
  'honestDisclaimer' : string,
  'recommendedPositionSize' : number,
  'regimeAssessment' : [] | [RegimeAssessment],
  'reasoning' : string,
  'grade' : SignalGrade,
  'modelSignal' : ModelSignal,
  'regimeLabel' : string,
  'expectedMovePercent' : number,
  'confluenceBreakdown' : Array<TimeframeVote>,
  'riskRewardRatio' : number,
  'compositeConfidence' : bigint,
  'calibratedConfidence' : [] | [CalibratedConfidence],
}
export type SignalType = { 'BuyPut' : null } |
  { 'Hold' : null } |
  { 'Sell' : null } |
  { 'BuyFutures' : null } |
  { 'BuyCall' : null };
export interface Stochastic {
  'overbought' : boolean,
  'percentD' : number,
  'percentK' : number,
  'oversold' : boolean,
}
export interface TechnicalIndicators {
  'atr' : ATR,
  'cci' : CCI,
  'rsi' : RSI,
  'bollinger' : BollingerBands,
  'macd' : MACD,
  'vwap' : VWAP,
  'stochastic' : Stochastic,
}
export type Timeframe = { 'D1' : null } |
  { 'H1' : null } |
  { 'H4' : null } |
  { 'M1' : null } |
  { 'M5' : null } |
  { 'W1' : null } |
  { 'M15' : null } |
  { 'M30' : null };
export interface TimeframeVote {
  'rsi' : number,
  'macdSignal' : number,
  'timeframe' : Timeframe,
  'bias' : string,
  'strength' : bigint,
  'keyLevel' : number,
  'vwapDev' : number,
}
export type Timestamp = bigint;
export type TradeStatus = { 'Win' : null } |
  { 'Loss' : null } |
  { 'Open' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface UserSettings { 'mode' : Mode, 'onboardingComplete' : boolean }
export interface VWAP {
  'value' : number,
  'deviation' : number,
  'lowerBand' : number,
  'upperBand' : number,
}
export interface VolatilityOverlay {
  'regime' : VolatilityRegime,
  'recommendedLeverage' : number,
  'riskAdjustedPositionSize' : number,
  'kellyFraction' : number,
  'regimeLabel' : string,
  'maxDrawdownEstimate' : number,
  'atrValue' : number,
}
export type VolatilityRegime = { 'LowVolatility' : null } |
  { 'HighVolatility' : null } |
  { 'Extreme' : null } |
  { 'Normal' : null };
export interface VolumeBin { 'volume' : number, 'price' : number }
export interface VolumeNode {
  'kind' : string,
  'volume' : number,
  'price' : number,
}
export interface VolumeProfile {
  'poc' : number,
  'vah' : number,
  'val' : number,
  'totalVolume' : number,
  'buyPressure' : number,
  'bins' : Array<VolumeBin>,
  'latestClose' : number,
  'maxPrice' : number,
  'lvnNodes' : Array<VolumeNode>,
  'hvnNodes' : Array<VolumeNode>,
  'pocVolume' : number,
  'minPrice' : number,
  'sellPressure' : number,
  'binCount' : bigint,
  'pricePosition' : PricePosition,
  'nodeClass' : NodeClass,
  'avgBinVolume' : number,
}
export interface _SERVICE {
  'addPracticeTrade' : ActorMethod<
    [string, string, string, Direction, number, number, number],
    PracticeTrade
  >,
  'addPredictionRecord' : ActorMethod<[PredictionRecord], bigint>,
  'adjustConfidenceForVolume' : ActorMethod<
    [number, string, VolumeProfile],
    number
  >,
  'calibrateConfidence' : ActorMethod<
    [number, [] | [string], [] | [Timeframe]],
    CalibratedConfidence
  >,
  'computeVolumeProfile' : ActorMethod<[string, string, bigint], VolumeProfile>,
  'detectRegime' : ActorMethod<[string, string], RegimeAssessment>,
  'generateMeanReversionSignal' : ActorMethod<
    [Array<OHLC>, QuantSettings],
    ModelSignal
  >,
  'generateModelSignal' : ActorMethod<
    [QuantModel, Array<OHLC>, [] | [Array<OHLC>], QuantSettings],
    ModelSignal
  >,
  'generateMomentumSignal' : ActorMethod<
    [Array<OHLC>, QuantSettings],
    ModelSignal
  >,
  'generatePairsSignal' : ActorMethod<
    [Array<OHLC>, Array<OHLC>, QuantSettings],
    ModelSignal
  >,
  'getBacktestHistory' : ActorMethod<[], Array<BacktestSummary>>,
  'getBacktestResult' : ActorMethod<[bigint], [] | [BacktestResult]>,
  'getCalibrationTable' : ActorMethod<
    [[] | [string], [] | [Timeframe]],
    CalibrationTable
  >,
  'getConfluenceResult' : ActorMethod<
    [string, Timeframe, string],
    ConfluenceResult
  >,
  'getCryptoOHLC' : ActorMethod<[string, bigint], Result>,
  'getCryptoPrice' : ActorMethod<[string], Result_1>,
  'getFilteredPredictionHistory' : ActorMethod<
    [PredictionFilter],
    Array<PredictionRecord>
  >,
  'getForexOHLC' : ActorMethod<[string, string, bigint], Result>,
  'getForexPrice' : ActorMethod<[string, string], Result_1>,
  'getIndianStockOHLC' : ActorMethod<[string, string], Result>,
  'getPracticeTradeHistory' : ActorMethod<[], Array<PracticeTrade>>,
  'getPracticeTradeStats' : ActorMethod<[], PracticeStats>,
  'getPredictionHistory' : ActorMethod<[], Array<PredictionRecord>>,
  'getPredictionStats' : ActorMethod<[], PredictionStats>,
  'getQuantSettings' : ActorMethod<[], QuantSettings>,
  'getRegimeHistory' : ActorMethod<
    [string, string, bigint],
    Array<RegimeHistoryEntry>
  >,
  'getRegimeStrategyWeights' : ActorMethod<
    [MarketRegime],
    RegimeStrategyWeights
  >,
  'getSignalReportCard' : ActorMethod<
    [string, Timeframe, string, number, number, [] | [QuantModel]],
    SignalReportCard
  >,
  'getTechnicalIndicators' : ActorMethod<
    [string, Timeframe, string],
    TechnicalIndicators
  >,
  'getUserSettings' : ActorMethod<[], UserSettings>,
  'getVolatilityOverlay' : ActorMethod<
    [string, Timeframe, string, number, number],
    VolatilityOverlay
  >,
  'getVolumeProfile' : ActorMethod<[string, string], VolumeProfile>,
  'manualResolvePredictionOutcome' : ActorMethod<
    [bigint, Outcome, number],
    boolean
  >,
  'resolvePracticeTradeFromPrice' : ActorMethod<
    [bigint, number],
    [] | [PracticeTrade]
  >,
  'resolvePredictionFromPrice' : ActorMethod<
    [bigint, string],
    [] | [[bigint, Outcome, number]]
  >,
  'resolvePredictionOutcome' : ActorMethod<
    [bigint, Outcome, number],
    undefined
  >,
  'runBacktest' : ActorMethod<[BacktestConfig], BacktestResult>,
  'runModelComparison' : ActorMethod<
    [
      AssetId,
      AssetClass,
      [] | [AssetId],
      Timeframe,
      Timestamp,
      Timestamp,
      number,
      QuantSettings,
    ],
    ModelComparison
  >,
  'selectBestModel' : ActorMethod<[AssetId, Timeframe], QuantModel>,
  'setMode' : ActorMethod<[Mode], undefined>,
  'setOnboardingComplete' : ActorMethod<[], undefined>,
  'setQuantSettings' : ActorMethod<[QuantSettings], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];