/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Direction = IDL.Variant({ 'Short' : IDL.Null, 'Long' : IDL.Null });
export const TradeStatus = IDL.Variant({
  'Win' : IDL.Null,
  'Loss' : IDL.Null,
  'Open' : IDL.Null,
});
export const PracticeTrade = IDL.Record({
  'id' : IDL.Nat,
  'pnl' : IDL.Opt(IDL.Float64),
  'status' : TradeStatus,
  'direction' : Direction,
  'assetId' : IDL.Text,
  'createdAt' : IDL.Nat,
  'targetPrice' : IDL.Float64,
  'scope' : IDL.Text,
  'stopLoss' : IDL.Float64,
  'timestamp' : IDL.Nat,
  'entryPrice' : IDL.Float64,
  'assetClass' : IDL.Text,
  'resolvedAt' : IDL.Opt(IDL.Nat),
});
export const Timeframe = IDL.Variant({
  'D1' : IDL.Null,
  'H1' : IDL.Null,
  'H4' : IDL.Null,
  'M1' : IDL.Null,
  'M5' : IDL.Null,
  'W1' : IDL.Null,
  'M15' : IDL.Null,
  'M30' : IDL.Null,
});
export const SignalGrade = IDL.Variant({
  'A' : IDL.Null,
  'B' : IDL.Null,
  'C' : IDL.Null,
  'D' : IDL.Null,
  'F' : IDL.Null,
});
export const SignalType = IDL.Variant({
  'BuyPut' : IDL.Null,
  'Hold' : IDL.Null,
  'Sell' : IDL.Null,
  'BuyFutures' : IDL.Null,
  'BuyCall' : IDL.Null,
});
export const Outcome = IDL.Variant({
  'Open' : IDL.Null,
  'HitTarget' : IDL.Null,
  'HitStop' : IDL.Null,
});
export const PredictionRecord = IDL.Record({
  'id' : IDL.Nat,
  'pnl' : IDL.Opt(IDL.Float64),
  'timeframe' : Timeframe,
  'assetId' : IDL.Text,
  'targetPrice' : IDL.Float64,
  'grade' : SignalGrade,
  'stopLoss' : IDL.Float64,
  'timestamp' : IDL.Nat,
  'entryPrice' : IDL.Float64,
  'signal' : SignalType,
  'confidence' : IDL.Nat,
  'outcome' : IDL.Opt(Outcome),
  'assetClass' : IDL.Text,
  'resolvedAt' : IDL.Opt(IDL.Nat),
});
export const VolumeBin = IDL.Record({
  'volume' : IDL.Float64,
  'price' : IDL.Float64,
});
export const VolumeNode = IDL.Record({
  'kind' : IDL.Text,
  'volume' : IDL.Float64,
  'price' : IDL.Float64,
});
export const PricePosition = IDL.Variant({
  'InVA' : IDL.Null,
  'BelowVA' : IDL.Null,
  'AboveVA' : IDL.Null,
});
export const NodeClass = IDL.Variant({
  'HVN' : IDL.Null,
  'LVN' : IDL.Null,
  'POC' : IDL.Null,
  'Other' : IDL.Null,
});
export const VolumeProfile = IDL.Record({
  'poc' : IDL.Float64,
  'vah' : IDL.Float64,
  'val' : IDL.Float64,
  'totalVolume' : IDL.Float64,
  'buyPressure' : IDL.Float64,
  'bins' : IDL.Vec(VolumeBin),
  'latestClose' : IDL.Float64,
  'maxPrice' : IDL.Float64,
  'lvnNodes' : IDL.Vec(VolumeNode),
  'hvnNodes' : IDL.Vec(VolumeNode),
  'pocVolume' : IDL.Float64,
  'minPrice' : IDL.Float64,
  'sellPressure' : IDL.Float64,
  'binCount' : IDL.Nat,
  'pricePosition' : PricePosition,
  'nodeClass' : NodeClass,
  'avgBinVolume' : IDL.Float64,
});
export const CalibrationBucket = IDL.Record({
  'realizedWinRate' : IDL.Float64,
  'reliabilityGrade' : IDL.Text,
  'reliabilityFactor' : IDL.Float64,
  'sampleCount' : IDL.Nat,
  'maxConfidence' : IDL.Float64,
  'minConfidence' : IDL.Float64,
});
export const CalibratedConfidence = IDL.Record({
  'warning' : IDL.Text,
  'isCalibrated' : IDL.Bool,
  'rawConfidence' : IDL.Float64,
  'bucket' : CalibrationBucket,
  'calibratedConfidence' : IDL.Float64,
});
export const MarketRegime = IDL.Variant({
  'trendingUp' : IDL.Null,
  'trendingDown' : IDL.Null,
  'volatile' : IDL.Null,
  'ranging' : IDL.Null,
});
export const RegimeAssessment = IDL.Record({
  'adx' : IDL.Float64,
  'regime' : MarketRegime,
  'plusDI' : IDL.Float64,
  'minusDI' : IDL.Float64,
  'reasoning' : IDL.Text,
  'atrPercentile' : IDL.Float64,
  'priceVsEma200' : IDL.Variant({
    'above' : IDL.Null,
    'near' : IDL.Null,
    'below' : IDL.Null,
  }),
  'confidence' : IDL.Float64,
});
export const OHLC = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'volume' : IDL.Float64,
  'timestamp' : IDL.Nat,
});
export const IndicatorSet = IDL.Variant({
  'Minimal' : IDL.Null,
  'Full' : IDL.Null,
});
export const ConfluenceWeights = IDL.Record({
  'd1' : IDL.Nat,
  'h1' : IDL.Nat,
  'h4' : IDL.Nat,
  'm15' : IDL.Nat,
  'lowerTimeframe' : IDL.Nat,
  'higherTimeframe' : IDL.Nat,
  'selectedTimeframe' : IDL.Nat,
});
export const QuantSettings = IDL.Record({
  'maxRiskPercent' : IDL.Float64,
  'useRegimeFilter' : IDL.Bool,
  'useVWAP' : IDL.Bool,
  'indicatorSet' : IndicatorSet,
  'accountSize' : IDL.Float64,
  'minConfidence' : IDL.Nat,
  'confluenceWeights' : ConfluenceWeights,
  'backtestLookback' : IDL.Nat,
});
export const QuantModel = IDL.Variant({
  'auto' : IDL.Null,
  'momentum' : IDL.Null,
  'meanReversion' : IDL.Null,
  'pairs' : IDL.Null,
});
export const ModelDirection = IDL.Variant({
  'long' : IDL.Null,
  'short' : IDL.Null,
  'neutral' : IDL.Null,
});
export const ModelSignal = IDL.Record({
  'model' : QuantModel,
  'direction' : ModelDirection,
  'metrics' : IDL.Text,
  'takeProfit' : IDL.Float64,
  'reasoning' : IDL.Text,
  'stopLoss' : IDL.Float64,
  'entryPrice' : IDL.Float64,
  'confidence' : IDL.Float64,
});
export const BacktestStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Partial' : IDL.Null,
  'Completed' : IDL.Null,
});
export const Timestamp = IDL.Nat;
export const CalibrationTable = IDL.Record({
  'totalSamples' : IDL.Nat,
  'lastUpdated' : Timestamp,
  'disclaimer' : IDL.Text,
  'buckets' : IDL.Vec(CalibrationBucket),
});
export const RegimePerformance = IDL.Record({
  'regime' : MarketRegime,
  'tradeCount' : IDL.Nat,
  'winRate' : IDL.Float64,
});
export const BacktestMetricsExtended = IDL.Record({
  'model' : QuantModel,
  'calibrationTable' : IDL.Opt(CalibrationTable),
  'numberOfTrades' : IDL.Nat,
  'outOfSampleWinRate' : IDL.Opt(IDL.Float64),
  'averageLoss' : IDL.Float64,
  'sharpeRatio' : IDL.Float64,
  'inSampleWinRate' : IDL.Opt(IDL.Float64),
  'averageWin' : IDL.Float64,
  'sortinoRatio' : IDL.Float64,
  'totalReturn' : IDL.Float64,
  'regimeBreakdown' : IDL.Opt(IDL.Vec(RegimePerformance)),
  'winRate' : IDL.Float64,
  'maxDrawdown' : IDL.Float64,
  'profitFactor' : IDL.Float64,
});
export const AssetId = IDL.Text;
export const AssetClass = IDL.Text;
export const BacktestConfig = IDL.Record({
  'model' : QuantModel,
  'pairsAssetId' : IDL.Opt(AssetId),
  'walkForwardSplit' : IDL.Float64,
  'endDate' : Timestamp,
  'timeframe' : Timeframe,
  'assetId' : AssetId,
  'strategyParams' : QuantSettings,
  'includeRegimeBreakdown' : IDL.Bool,
  'runLabel' : IDL.Opt(IDL.Text),
  'initialCapital' : IDL.Float64,
  'assetClass' : AssetClass,
  'startDate' : Timestamp,
});
export const BacktestSummary = IDL.Record({
  'id' : IDL.Nat,
  'status' : BacktestStatus,
  'metrics' : BacktestMetricsExtended,
  'tradeCount' : IDL.Nat,
  'runLabel' : IDL.Opt(IDL.Text),
  'config' : BacktestConfig,
  'runAt' : Timestamp,
});
export const BacktestDirection = IDL.Variant({
  'Short' : IDL.Null,
  'Long' : IDL.Null,
});
export const BacktestTrade = IDL.Record({
  'pnl' : IDL.Float64,
  'direction' : BacktestDirection,
  'returnPercent' : IDL.Float64,
  'entryTimestamp' : Timestamp,
  'holdingPeriod' : IDL.Nat,
  'exitTimestamp' : Timestamp,
  'entryPrice' : IDL.Float64,
  'exitPrice' : IDL.Float64,
});
export const EquityPoint = IDL.Record({
  'drawdown' : IDL.Float64,
  'timestamp' : Timestamp,
  'equity' : IDL.Float64,
});
export const BacktestResult = IDL.Record({
  'metrics' : BacktestMetricsExtended,
  'trades' : IDL.Vec(BacktestTrade),
  'equityCurve' : IDL.Vec(EquityPoint),
  'config' : BacktestConfig,
  'runAt' : Timestamp,
});
export const TimeframeVote = IDL.Record({
  'rsi' : IDL.Float64,
  'macdSignal' : IDL.Float64,
  'timeframe' : Timeframe,
  'bias' : IDL.Text,
  'strength' : IDL.Nat,
  'keyLevel' : IDL.Float64,
  'vwapDev' : IDL.Float64,
});
export const ConfluenceResult = IDL.Record({
  'primaryTimeframe' : Timeframe,
  'votes' : IDL.Vec(TimeframeVote),
  'finalBias' : IDL.Text,
  'weightedScore' : IDL.Float64,
  'confluenceScore' : IDL.Nat,
});
export const Result = IDL.Variant({ 'Ok' : IDL.Vec(OHLC), 'Err' : IDL.Text });
export const Result_1 = IDL.Variant({ 'Ok' : IDL.Float64, 'Err' : IDL.Text });
export const PredictionFilter = IDL.Record({
  'endDate' : IDL.Opt(IDL.Nat),
  'timeframe' : IDL.Opt(Timeframe),
  'assetId' : IDL.Opt(IDL.Text),
  'grade' : IDL.Opt(SignalGrade),
  'outcome' : IDL.Opt(Outcome),
  'signalType' : IDL.Opt(SignalType),
  'startDate' : IDL.Opt(IDL.Nat),
});
export const PracticeStats = IDL.Record({
  'avgRiskReward' : IDL.Float64,
  'totalTrades' : IDL.Nat,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'totalPnl' : IDL.Float64,
  'winRate' : IDL.Float64,
  'avgPnl' : IDL.Float64,
});
export const GradeDistribution = IDL.Record({
  'gradeA' : IDL.Nat,
  'gradeB' : IDL.Nat,
  'gradeC' : IDL.Nat,
  'gradeD' : IDL.Nat,
  'gradeF' : IDL.Nat,
});
export const OutcomeBreakdown = IDL.Record({
  'open' : IDL.Nat,
  'hitTarget' : IDL.Nat,
  'hitStop' : IDL.Nat,
});
export const PredictionStats = IDL.Record({
  'avgRiskReward' : IDL.Float64,
  'bestTrade' : IDL.Float64,
  'worstTrade' : IDL.Float64,
  'gradeDistribution' : GradeDistribution,
  'sharpeLikeRatio' : IDL.Float64,
  'totalPredictions' : IDL.Nat,
  'outcomeBreakdown' : OutcomeBreakdown,
  'winRate' : IDL.Float64,
  'resolvedCount' : IDL.Nat,
  'avgPnl' : IDL.Float64,
});
export const RegimeHistoryEntry = IDL.Record({
  'regime' : MarketRegime,
  'timestamp' : Timestamp,
});
export const RegimeStrategyWeights = IDL.Record({
  'sizeMultiplier' : IDL.Float64,
  'momentum' : IDL.Float64,
  'meanReversion' : IDL.Float64,
  'pairs' : IDL.Float64,
});
export const VolatilityRegime = IDL.Variant({
  'LowVolatility' : IDL.Null,
  'HighVolatility' : IDL.Null,
  'Extreme' : IDL.Null,
  'Normal' : IDL.Null,
});
export const BacktestMetrics = IDL.Record({
  'avgReturn' : IDL.Float64,
  'sharpeRatio' : IDL.Float64,
  'winRate' : IDL.Float64,
  'maxDrawdown' : IDL.Float64,
  'lookbackCandles' : IDL.Nat,
});
export const KeyLevel = IDL.Record({
  'kind' : IDL.Text,
  'name' : IDL.Text,
  'price' : IDL.Float64,
});
export const SignalReportCard = IDL.Record({
  'regime' : VolatilityRegime,
  'volumeProfile' : IDL.Opt(VolumeProfile),
  'model' : QuantModel,
  'backtest' : BacktestMetrics,
  'expectedValue' : IDL.Float64,
  'keyLevels' : IDL.Vec(KeyLevel),
  'bias' : IDL.Text,
  'honestDisclaimer' : IDL.Text,
  'recommendedPositionSize' : IDL.Float64,
  'regimeAssessment' : IDL.Opt(RegimeAssessment),
  'reasoning' : IDL.Text,
  'grade' : SignalGrade,
  'modelSignal' : ModelSignal,
  'regimeLabel' : IDL.Text,
  'expectedMovePercent' : IDL.Float64,
  'confluenceBreakdown' : IDL.Vec(TimeframeVote),
  'riskRewardRatio' : IDL.Float64,
  'compositeConfidence' : IDL.Nat,
  'calibratedConfidence' : IDL.Opt(CalibratedConfidence),
});
export const ATR = IDL.Record({ 'value' : IDL.Float64 });
export const CCI = IDL.Record({
  'overbought' : IDL.Bool,
  'value' : IDL.Float64,
  'oversold' : IDL.Bool,
});
export const RSI = IDL.Record({
  'overbought' : IDL.Bool,
  'value' : IDL.Float64,
  'oversold' : IDL.Bool,
});
export const BollingerBands = IDL.Record({
  'percentB' : IDL.Float64,
  'middle' : IDL.Float64,
  'lower' : IDL.Float64,
  'upper' : IDL.Float64,
});
export const MACD = IDL.Record({
  'histogram' : IDL.Float64,
  'macdLine' : IDL.Float64,
  'signalLine' : IDL.Float64,
});
export const VWAP = IDL.Record({
  'value' : IDL.Float64,
  'deviation' : IDL.Float64,
  'lowerBand' : IDL.Float64,
  'upperBand' : IDL.Float64,
});
export const Stochastic = IDL.Record({
  'overbought' : IDL.Bool,
  'percentD' : IDL.Float64,
  'percentK' : IDL.Float64,
  'oversold' : IDL.Bool,
});
export const TechnicalIndicators = IDL.Record({
  'atr' : ATR,
  'cci' : CCI,
  'rsi' : RSI,
  'bollinger' : BollingerBands,
  'macd' : MACD,
  'vwap' : VWAP,
  'stochastic' : Stochastic,
});
export const Mode = IDL.Variant({
  'Beginner' : IDL.Null,
  'Advanced' : IDL.Null,
  'PowerUser' : IDL.Null,
  'Intermediate' : IDL.Null,
  'Optional' : IDL.Null,
});
export const UserSettings = IDL.Record({
  'mode' : Mode,
  'onboardingComplete' : IDL.Bool,
});
export const VolatilityOverlay = IDL.Record({
  'regime' : VolatilityRegime,
  'recommendedLeverage' : IDL.Float64,
  'riskAdjustedPositionSize' : IDL.Float64,
  'kellyFraction' : IDL.Float64,
  'regimeLabel' : IDL.Text,
  'maxDrawdownEstimate' : IDL.Float64,
  'atrValue' : IDL.Float64,
});
export const ModelComparisonEntry = IDL.Record({
  'totalTrades' : IDL.Nat,
  'model' : QuantModel,
  'sharpe' : IDL.Float64,
  'outOfSampleWinRate' : IDL.Opt(IDL.Float64),
  'winRate' : IDL.Float64,
  'maxDrawdown' : IDL.Float64,
  'profitFactor' : IDL.Float64,
});
export const ModelComparison = IDL.Record({
  'timeframe' : Timeframe,
  'assetId' : AssetId,
  'results' : IDL.Vec(ModelComparisonEntry),
  'dateRange' : IDL.Text,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  'addPracticeTrade' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Direction,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [PracticeTrade],
      [],
    ),
  'addPredictionRecord' : IDL.Func([PredictionRecord], [IDL.Nat], []),
  'adjustConfidenceForVolume' : IDL.Func(
      [IDL.Float64, IDL.Text, VolumeProfile],
      [IDL.Float64],
      ['query'],
    ),
  'calibrateConfidence' : IDL.Func(
      [IDL.Float64, IDL.Opt(IDL.Text), IDL.Opt(Timeframe)],
      [CalibratedConfidence],
      ['query'],
    ),
  'computeVolumeProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [VolumeProfile],
      [],
    ),
  'detectRegime' : IDL.Func([IDL.Text, IDL.Text], [RegimeAssessment], []),
  'generateMeanReversionSignal' : IDL.Func(
      [IDL.Vec(OHLC), QuantSettings],
      [ModelSignal],
      [],
    ),
  'generateModelSignal' : IDL.Func(
      [QuantModel, IDL.Vec(OHLC), IDL.Opt(IDL.Vec(OHLC)), QuantSettings],
      [ModelSignal],
      [],
    ),
  'generateMomentumSignal' : IDL.Func(
      [IDL.Vec(OHLC), QuantSettings],
      [ModelSignal],
      [],
    ),
  'generatePairsSignal' : IDL.Func(
      [IDL.Vec(OHLC), IDL.Vec(OHLC), QuantSettings],
      [ModelSignal],
      [],
    ),
  'getBacktestHistory' : IDL.Func([], [IDL.Vec(BacktestSummary)], ['query']),
  'getBacktestResult' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(BacktestResult)],
      ['query'],
    ),
  'getCalibrationTable' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(Timeframe)],
      [CalibrationTable],
      ['query'],
    ),
  'getConfluenceResult' : IDL.Func(
      [IDL.Text, Timeframe, IDL.Text],
      [ConfluenceResult],
      [],
    ),
  'getCryptoOHLC' : IDL.Func([IDL.Text, IDL.Nat], [Result], []),
  'getCryptoPrice' : IDL.Func([IDL.Text], [Result_1], []),
  'getFilteredPredictionHistory' : IDL.Func(
      [PredictionFilter],
      [IDL.Vec(PredictionRecord)],
      ['query'],
    ),
  'getForexOHLC' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Result], []),
  'getForexPrice' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'getIndianStockOHLC' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'getPracticeTradeHistory' : IDL.Func([], [IDL.Vec(PracticeTrade)], ['query']),
  'getPracticeTradeStats' : IDL.Func([], [PracticeStats], ['query']),
  'getPredictionHistory' : IDL.Func([], [IDL.Vec(PredictionRecord)], ['query']),
  'getPredictionStats' : IDL.Func([], [PredictionStats], ['query']),
  'getQuantSettings' : IDL.Func([], [QuantSettings], ['query']),
  'getRegimeHistory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Vec(RegimeHistoryEntry)],
      [],
    ),
  'getRegimeStrategyWeights' : IDL.Func(
      [MarketRegime],
      [RegimeStrategyWeights],
      ['query'],
    ),
  'getSignalReportCard' : IDL.Func(
      [
        IDL.Text,
        Timeframe,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(QuantModel),
      ],
      [SignalReportCard],
      [],
    ),
  'getTechnicalIndicators' : IDL.Func(
      [IDL.Text, Timeframe, IDL.Text],
      [TechnicalIndicators],
      [],
    ),
  'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
  'getVolatilityOverlay' : IDL.Func(
      [IDL.Text, Timeframe, IDL.Text, IDL.Float64, IDL.Float64],
      [VolatilityOverlay],
      [],
    ),
  'getVolumeProfile' : IDL.Func([IDL.Text, IDL.Text], [VolumeProfile], []),
  'manualResolvePredictionOutcome' : IDL.Func(
      [IDL.Nat, Outcome, IDL.Float64],
      [IDL.Bool],
      [],
    ),
  'resolvePracticeTradeFromPrice' : IDL.Func(
      [IDL.Nat, IDL.Float64],
      [IDL.Opt(PracticeTrade)],
      [],
    ),
  'resolvePredictionFromPrice' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(IDL.Tuple(IDL.Nat, Outcome, IDL.Float64))],
      [],
    ),
  'resolvePredictionOutcome' : IDL.Func(
      [IDL.Nat, Outcome, IDL.Float64],
      [],
      [],
    ),
  'runBacktest' : IDL.Func([BacktestConfig], [BacktestResult], []),
  'runModelComparison' : IDL.Func(
      [
        AssetId,
        AssetClass,
        IDL.Opt(AssetId),
        Timeframe,
        Timestamp,
        Timestamp,
        IDL.Float64,
        QuantSettings,
      ],
      [ModelComparison],
      [],
    ),
  'selectBestModel' : IDL.Func([AssetId, Timeframe], [QuantModel], ['query']),
  'setMode' : IDL.Func([Mode], [], []),
  'setOnboardingComplete' : IDL.Func([], [], []),
  'setQuantSettings' : IDL.Func([QuantSettings], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Direction = IDL.Variant({ 'Short' : IDL.Null, 'Long' : IDL.Null });
  const TradeStatus = IDL.Variant({
    'Win' : IDL.Null,
    'Loss' : IDL.Null,
    'Open' : IDL.Null,
  });
  const PracticeTrade = IDL.Record({
    'id' : IDL.Nat,
    'pnl' : IDL.Opt(IDL.Float64),
    'status' : TradeStatus,
    'direction' : Direction,
    'assetId' : IDL.Text,
    'createdAt' : IDL.Nat,
    'targetPrice' : IDL.Float64,
    'scope' : IDL.Text,
    'stopLoss' : IDL.Float64,
    'timestamp' : IDL.Nat,
    'entryPrice' : IDL.Float64,
    'assetClass' : IDL.Text,
    'resolvedAt' : IDL.Opt(IDL.Nat),
  });
  const Timeframe = IDL.Variant({
    'D1' : IDL.Null,
    'H1' : IDL.Null,
    'H4' : IDL.Null,
    'M1' : IDL.Null,
    'M5' : IDL.Null,
    'W1' : IDL.Null,
    'M15' : IDL.Null,
    'M30' : IDL.Null,
  });
  const SignalGrade = IDL.Variant({
    'A' : IDL.Null,
    'B' : IDL.Null,
    'C' : IDL.Null,
    'D' : IDL.Null,
    'F' : IDL.Null,
  });
  const SignalType = IDL.Variant({
    'BuyPut' : IDL.Null,
    'Hold' : IDL.Null,
    'Sell' : IDL.Null,
    'BuyFutures' : IDL.Null,
    'BuyCall' : IDL.Null,
  });
  const Outcome = IDL.Variant({
    'Open' : IDL.Null,
    'HitTarget' : IDL.Null,
    'HitStop' : IDL.Null,
  });
  const PredictionRecord = IDL.Record({
    'id' : IDL.Nat,
    'pnl' : IDL.Opt(IDL.Float64),
    'timeframe' : Timeframe,
    'assetId' : IDL.Text,
    'targetPrice' : IDL.Float64,
    'grade' : SignalGrade,
    'stopLoss' : IDL.Float64,
    'timestamp' : IDL.Nat,
    'entryPrice' : IDL.Float64,
    'signal' : SignalType,
    'confidence' : IDL.Nat,
    'outcome' : IDL.Opt(Outcome),
    'assetClass' : IDL.Text,
    'resolvedAt' : IDL.Opt(IDL.Nat),
  });
  const VolumeBin = IDL.Record({
    'volume' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const VolumeNode = IDL.Record({
    'kind' : IDL.Text,
    'volume' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const PricePosition = IDL.Variant({
    'InVA' : IDL.Null,
    'BelowVA' : IDL.Null,
    'AboveVA' : IDL.Null,
  });
  const NodeClass = IDL.Variant({
    'HVN' : IDL.Null,
    'LVN' : IDL.Null,
    'POC' : IDL.Null,
    'Other' : IDL.Null,
  });
  const VolumeProfile = IDL.Record({
    'poc' : IDL.Float64,
    'vah' : IDL.Float64,
    'val' : IDL.Float64,
    'totalVolume' : IDL.Float64,
    'buyPressure' : IDL.Float64,
    'bins' : IDL.Vec(VolumeBin),
    'latestClose' : IDL.Float64,
    'maxPrice' : IDL.Float64,
    'lvnNodes' : IDL.Vec(VolumeNode),
    'hvnNodes' : IDL.Vec(VolumeNode),
    'pocVolume' : IDL.Float64,
    'minPrice' : IDL.Float64,
    'sellPressure' : IDL.Float64,
    'binCount' : IDL.Nat,
    'pricePosition' : PricePosition,
    'nodeClass' : NodeClass,
    'avgBinVolume' : IDL.Float64,
  });
  const CalibrationBucket = IDL.Record({
    'realizedWinRate' : IDL.Float64,
    'reliabilityGrade' : IDL.Text,
    'reliabilityFactor' : IDL.Float64,
    'sampleCount' : IDL.Nat,
    'maxConfidence' : IDL.Float64,
    'minConfidence' : IDL.Float64,
  });
  const CalibratedConfidence = IDL.Record({
    'warning' : IDL.Text,
    'isCalibrated' : IDL.Bool,
    'rawConfidence' : IDL.Float64,
    'bucket' : CalibrationBucket,
    'calibratedConfidence' : IDL.Float64,
  });
  const MarketRegime = IDL.Variant({
    'trendingUp' : IDL.Null,
    'trendingDown' : IDL.Null,
    'volatile' : IDL.Null,
    'ranging' : IDL.Null,
  });
  const RegimeAssessment = IDL.Record({
    'adx' : IDL.Float64,
    'regime' : MarketRegime,
    'plusDI' : IDL.Float64,
    'minusDI' : IDL.Float64,
    'reasoning' : IDL.Text,
    'atrPercentile' : IDL.Float64,
    'priceVsEma200' : IDL.Variant({
      'above' : IDL.Null,
      'near' : IDL.Null,
      'below' : IDL.Null,
    }),
    'confidence' : IDL.Float64,
  });
  const OHLC = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'volume' : IDL.Float64,
    'timestamp' : IDL.Nat,
  });
  const IndicatorSet = IDL.Variant({ 'Minimal' : IDL.Null, 'Full' : IDL.Null });
  const ConfluenceWeights = IDL.Record({
    'd1' : IDL.Nat,
    'h1' : IDL.Nat,
    'h4' : IDL.Nat,
    'm15' : IDL.Nat,
    'lowerTimeframe' : IDL.Nat,
    'higherTimeframe' : IDL.Nat,
    'selectedTimeframe' : IDL.Nat,
  });
  const QuantSettings = IDL.Record({
    'maxRiskPercent' : IDL.Float64,
    'useRegimeFilter' : IDL.Bool,
    'useVWAP' : IDL.Bool,
    'indicatorSet' : IndicatorSet,
    'accountSize' : IDL.Float64,
    'minConfidence' : IDL.Nat,
    'confluenceWeights' : ConfluenceWeights,
    'backtestLookback' : IDL.Nat,
  });
  const QuantModel = IDL.Variant({
    'auto' : IDL.Null,
    'momentum' : IDL.Null,
    'meanReversion' : IDL.Null,
    'pairs' : IDL.Null,
  });
  const ModelDirection = IDL.Variant({
    'long' : IDL.Null,
    'short' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const ModelSignal = IDL.Record({
    'model' : QuantModel,
    'direction' : ModelDirection,
    'metrics' : IDL.Text,
    'takeProfit' : IDL.Float64,
    'reasoning' : IDL.Text,
    'stopLoss' : IDL.Float64,
    'entryPrice' : IDL.Float64,
    'confidence' : IDL.Float64,
  });
  const BacktestStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Partial' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const Timestamp = IDL.Nat;
  const CalibrationTable = IDL.Record({
    'totalSamples' : IDL.Nat,
    'lastUpdated' : Timestamp,
    'disclaimer' : IDL.Text,
    'buckets' : IDL.Vec(CalibrationBucket),
  });
  const RegimePerformance = IDL.Record({
    'regime' : MarketRegime,
    'tradeCount' : IDL.Nat,
    'winRate' : IDL.Float64,
  });
  const BacktestMetricsExtended = IDL.Record({
    'model' : QuantModel,
    'calibrationTable' : IDL.Opt(CalibrationTable),
    'numberOfTrades' : IDL.Nat,
    'outOfSampleWinRate' : IDL.Opt(IDL.Float64),
    'averageLoss' : IDL.Float64,
    'sharpeRatio' : IDL.Float64,
    'inSampleWinRate' : IDL.Opt(IDL.Float64),
    'averageWin' : IDL.Float64,
    'sortinoRatio' : IDL.Float64,
    'totalReturn' : IDL.Float64,
    'regimeBreakdown' : IDL.Opt(IDL.Vec(RegimePerformance)),
    'winRate' : IDL.Float64,
    'maxDrawdown' : IDL.Float64,
    'profitFactor' : IDL.Float64,
  });
  const AssetId = IDL.Text;
  const AssetClass = IDL.Text;
  const BacktestConfig = IDL.Record({
    'model' : QuantModel,
    'pairsAssetId' : IDL.Opt(AssetId),
    'walkForwardSplit' : IDL.Float64,
    'endDate' : Timestamp,
    'timeframe' : Timeframe,
    'assetId' : AssetId,
    'strategyParams' : QuantSettings,
    'includeRegimeBreakdown' : IDL.Bool,
    'runLabel' : IDL.Opt(IDL.Text),
    'initialCapital' : IDL.Float64,
    'assetClass' : AssetClass,
    'startDate' : Timestamp,
  });
  const BacktestSummary = IDL.Record({
    'id' : IDL.Nat,
    'status' : BacktestStatus,
    'metrics' : BacktestMetricsExtended,
    'tradeCount' : IDL.Nat,
    'runLabel' : IDL.Opt(IDL.Text),
    'config' : BacktestConfig,
    'runAt' : Timestamp,
  });
  const BacktestDirection = IDL.Variant({
    'Short' : IDL.Null,
    'Long' : IDL.Null,
  });
  const BacktestTrade = IDL.Record({
    'pnl' : IDL.Float64,
    'direction' : BacktestDirection,
    'returnPercent' : IDL.Float64,
    'entryTimestamp' : Timestamp,
    'holdingPeriod' : IDL.Nat,
    'exitTimestamp' : Timestamp,
    'entryPrice' : IDL.Float64,
    'exitPrice' : IDL.Float64,
  });
  const EquityPoint = IDL.Record({
    'drawdown' : IDL.Float64,
    'timestamp' : Timestamp,
    'equity' : IDL.Float64,
  });
  const BacktestResult = IDL.Record({
    'metrics' : BacktestMetricsExtended,
    'trades' : IDL.Vec(BacktestTrade),
    'equityCurve' : IDL.Vec(EquityPoint),
    'config' : BacktestConfig,
    'runAt' : Timestamp,
  });
  const TimeframeVote = IDL.Record({
    'rsi' : IDL.Float64,
    'macdSignal' : IDL.Float64,
    'timeframe' : Timeframe,
    'bias' : IDL.Text,
    'strength' : IDL.Nat,
    'keyLevel' : IDL.Float64,
    'vwapDev' : IDL.Float64,
  });
  const ConfluenceResult = IDL.Record({
    'primaryTimeframe' : Timeframe,
    'votes' : IDL.Vec(TimeframeVote),
    'finalBias' : IDL.Text,
    'weightedScore' : IDL.Float64,
    'confluenceScore' : IDL.Nat,
  });
  const Result = IDL.Variant({ 'Ok' : IDL.Vec(OHLC), 'Err' : IDL.Text });
  const Result_1 = IDL.Variant({ 'Ok' : IDL.Float64, 'Err' : IDL.Text });
  const PredictionFilter = IDL.Record({
    'endDate' : IDL.Opt(IDL.Nat),
    'timeframe' : IDL.Opt(Timeframe),
    'assetId' : IDL.Opt(IDL.Text),
    'grade' : IDL.Opt(SignalGrade),
    'outcome' : IDL.Opt(Outcome),
    'signalType' : IDL.Opt(SignalType),
    'startDate' : IDL.Opt(IDL.Nat),
  });
  const PracticeStats = IDL.Record({
    'avgRiskReward' : IDL.Float64,
    'totalTrades' : IDL.Nat,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'totalPnl' : IDL.Float64,
    'winRate' : IDL.Float64,
    'avgPnl' : IDL.Float64,
  });
  const GradeDistribution = IDL.Record({
    'gradeA' : IDL.Nat,
    'gradeB' : IDL.Nat,
    'gradeC' : IDL.Nat,
    'gradeD' : IDL.Nat,
    'gradeF' : IDL.Nat,
  });
  const OutcomeBreakdown = IDL.Record({
    'open' : IDL.Nat,
    'hitTarget' : IDL.Nat,
    'hitStop' : IDL.Nat,
  });
  const PredictionStats = IDL.Record({
    'avgRiskReward' : IDL.Float64,
    'bestTrade' : IDL.Float64,
    'worstTrade' : IDL.Float64,
    'gradeDistribution' : GradeDistribution,
    'sharpeLikeRatio' : IDL.Float64,
    'totalPredictions' : IDL.Nat,
    'outcomeBreakdown' : OutcomeBreakdown,
    'winRate' : IDL.Float64,
    'resolvedCount' : IDL.Nat,
    'avgPnl' : IDL.Float64,
  });
  const RegimeHistoryEntry = IDL.Record({
    'regime' : MarketRegime,
    'timestamp' : Timestamp,
  });
  const RegimeStrategyWeights = IDL.Record({
    'sizeMultiplier' : IDL.Float64,
    'momentum' : IDL.Float64,
    'meanReversion' : IDL.Float64,
    'pairs' : IDL.Float64,
  });
  const VolatilityRegime = IDL.Variant({
    'LowVolatility' : IDL.Null,
    'HighVolatility' : IDL.Null,
    'Extreme' : IDL.Null,
    'Normal' : IDL.Null,
  });
  const BacktestMetrics = IDL.Record({
    'avgReturn' : IDL.Float64,
    'sharpeRatio' : IDL.Float64,
    'winRate' : IDL.Float64,
    'maxDrawdown' : IDL.Float64,
    'lookbackCandles' : IDL.Nat,
  });
  const KeyLevel = IDL.Record({
    'kind' : IDL.Text,
    'name' : IDL.Text,
    'price' : IDL.Float64,
  });
  const SignalReportCard = IDL.Record({
    'regime' : VolatilityRegime,
    'volumeProfile' : IDL.Opt(VolumeProfile),
    'model' : QuantModel,
    'backtest' : BacktestMetrics,
    'expectedValue' : IDL.Float64,
    'keyLevels' : IDL.Vec(KeyLevel),
    'bias' : IDL.Text,
    'honestDisclaimer' : IDL.Text,
    'recommendedPositionSize' : IDL.Float64,
    'regimeAssessment' : IDL.Opt(RegimeAssessment),
    'reasoning' : IDL.Text,
    'grade' : SignalGrade,
    'modelSignal' : ModelSignal,
    'regimeLabel' : IDL.Text,
    'expectedMovePercent' : IDL.Float64,
    'confluenceBreakdown' : IDL.Vec(TimeframeVote),
    'riskRewardRatio' : IDL.Float64,
    'compositeConfidence' : IDL.Nat,
    'calibratedConfidence' : IDL.Opt(CalibratedConfidence),
  });
  const ATR = IDL.Record({ 'value' : IDL.Float64 });
  const CCI = IDL.Record({
    'overbought' : IDL.Bool,
    'value' : IDL.Float64,
    'oversold' : IDL.Bool,
  });
  const RSI = IDL.Record({
    'overbought' : IDL.Bool,
    'value' : IDL.Float64,
    'oversold' : IDL.Bool,
  });
  const BollingerBands = IDL.Record({
    'percentB' : IDL.Float64,
    'middle' : IDL.Float64,
    'lower' : IDL.Float64,
    'upper' : IDL.Float64,
  });
  const MACD = IDL.Record({
    'histogram' : IDL.Float64,
    'macdLine' : IDL.Float64,
    'signalLine' : IDL.Float64,
  });
  const VWAP = IDL.Record({
    'value' : IDL.Float64,
    'deviation' : IDL.Float64,
    'lowerBand' : IDL.Float64,
    'upperBand' : IDL.Float64,
  });
  const Stochastic = IDL.Record({
    'overbought' : IDL.Bool,
    'percentD' : IDL.Float64,
    'percentK' : IDL.Float64,
    'oversold' : IDL.Bool,
  });
  const TechnicalIndicators = IDL.Record({
    'atr' : ATR,
    'cci' : CCI,
    'rsi' : RSI,
    'bollinger' : BollingerBands,
    'macd' : MACD,
    'vwap' : VWAP,
    'stochastic' : Stochastic,
  });
  const Mode = IDL.Variant({
    'Beginner' : IDL.Null,
    'Advanced' : IDL.Null,
    'PowerUser' : IDL.Null,
    'Intermediate' : IDL.Null,
    'Optional' : IDL.Null,
  });
  const UserSettings = IDL.Record({
    'mode' : Mode,
    'onboardingComplete' : IDL.Bool,
  });
  const VolatilityOverlay = IDL.Record({
    'regime' : VolatilityRegime,
    'recommendedLeverage' : IDL.Float64,
    'riskAdjustedPositionSize' : IDL.Float64,
    'kellyFraction' : IDL.Float64,
    'regimeLabel' : IDL.Text,
    'maxDrawdownEstimate' : IDL.Float64,
    'atrValue' : IDL.Float64,
  });
  const ModelComparisonEntry = IDL.Record({
    'totalTrades' : IDL.Nat,
    'model' : QuantModel,
    'sharpe' : IDL.Float64,
    'outOfSampleWinRate' : IDL.Opt(IDL.Float64),
    'winRate' : IDL.Float64,
    'maxDrawdown' : IDL.Float64,
    'profitFactor' : IDL.Float64,
  });
  const ModelComparison = IDL.Record({
    'timeframe' : Timeframe,
    'assetId' : AssetId,
    'results' : IDL.Vec(ModelComparisonEntry),
    'dateRange' : IDL.Text,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    'addPracticeTrade' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Direction,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [PracticeTrade],
        [],
      ),
    'addPredictionRecord' : IDL.Func([PredictionRecord], [IDL.Nat], []),
    'adjustConfidenceForVolume' : IDL.Func(
        [IDL.Float64, IDL.Text, VolumeProfile],
        [IDL.Float64],
        ['query'],
      ),
    'calibrateConfidence' : IDL.Func(
        [IDL.Float64, IDL.Opt(IDL.Text), IDL.Opt(Timeframe)],
        [CalibratedConfidence],
        ['query'],
      ),
    'computeVolumeProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [VolumeProfile],
        [],
      ),
    'detectRegime' : IDL.Func([IDL.Text, IDL.Text], [RegimeAssessment], []),
    'generateMeanReversionSignal' : IDL.Func(
        [IDL.Vec(OHLC), QuantSettings],
        [ModelSignal],
        [],
      ),
    'generateModelSignal' : IDL.Func(
        [QuantModel, IDL.Vec(OHLC), IDL.Opt(IDL.Vec(OHLC)), QuantSettings],
        [ModelSignal],
        [],
      ),
    'generateMomentumSignal' : IDL.Func(
        [IDL.Vec(OHLC), QuantSettings],
        [ModelSignal],
        [],
      ),
    'generatePairsSignal' : IDL.Func(
        [IDL.Vec(OHLC), IDL.Vec(OHLC), QuantSettings],
        [ModelSignal],
        [],
      ),
    'getBacktestHistory' : IDL.Func([], [IDL.Vec(BacktestSummary)], ['query']),
    'getBacktestResult' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(BacktestResult)],
        ['query'],
      ),
    'getCalibrationTable' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(Timeframe)],
        [CalibrationTable],
        ['query'],
      ),
    'getConfluenceResult' : IDL.Func(
        [IDL.Text, Timeframe, IDL.Text],
        [ConfluenceResult],
        [],
      ),
    'getCryptoOHLC' : IDL.Func([IDL.Text, IDL.Nat], [Result], []),
    'getCryptoPrice' : IDL.Func([IDL.Text], [Result_1], []),
    'getFilteredPredictionHistory' : IDL.Func(
        [PredictionFilter],
        [IDL.Vec(PredictionRecord)],
        ['query'],
      ),
    'getForexOHLC' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Result], []),
    'getForexPrice' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'getIndianStockOHLC' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'getPracticeTradeHistory' : IDL.Func(
        [],
        [IDL.Vec(PracticeTrade)],
        ['query'],
      ),
    'getPracticeTradeStats' : IDL.Func([], [PracticeStats], ['query']),
    'getPredictionHistory' : IDL.Func(
        [],
        [IDL.Vec(PredictionRecord)],
        ['query'],
      ),
    'getPredictionStats' : IDL.Func([], [PredictionStats], ['query']),
    'getQuantSettings' : IDL.Func([], [QuantSettings], ['query']),
    'getRegimeHistory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Vec(RegimeHistoryEntry)],
        [],
      ),
    'getRegimeStrategyWeights' : IDL.Func(
        [MarketRegime],
        [RegimeStrategyWeights],
        ['query'],
      ),
    'getSignalReportCard' : IDL.Func(
        [
          IDL.Text,
          Timeframe,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(QuantModel),
        ],
        [SignalReportCard],
        [],
      ),
    'getTechnicalIndicators' : IDL.Func(
        [IDL.Text, Timeframe, IDL.Text],
        [TechnicalIndicators],
        [],
      ),
    'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
    'getVolatilityOverlay' : IDL.Func(
        [IDL.Text, Timeframe, IDL.Text, IDL.Float64, IDL.Float64],
        [VolatilityOverlay],
        [],
      ),
    'getVolumeProfile' : IDL.Func([IDL.Text, IDL.Text], [VolumeProfile], []),
    'manualResolvePredictionOutcome' : IDL.Func(
        [IDL.Nat, Outcome, IDL.Float64],
        [IDL.Bool],
        [],
      ),
    'resolvePracticeTradeFromPrice' : IDL.Func(
        [IDL.Nat, IDL.Float64],
        [IDL.Opt(PracticeTrade)],
        [],
      ),
    'resolvePredictionFromPrice' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(IDL.Tuple(IDL.Nat, Outcome, IDL.Float64))],
        [],
      ),
    'resolvePredictionOutcome' : IDL.Func(
        [IDL.Nat, Outcome, IDL.Float64],
        [],
        [],
      ),
    'runBacktest' : IDL.Func([BacktestConfig], [BacktestResult], []),
    'runModelComparison' : IDL.Func(
        [
          AssetId,
          AssetClass,
          IDL.Opt(AssetId),
          Timeframe,
          Timestamp,
          Timestamp,
          IDL.Float64,
          QuantSettings,
        ],
        [ModelComparison],
        [],
      ),
    'selectBestModel' : IDL.Func([AssetId, Timeframe], [QuantModel], ['query']),
    'setMode' : IDL.Func([Mode], [], []),
    'setOnboardingComplete' : IDL.Func([], [], []),
    'setQuantSettings' : IDL.Func([QuantSettings], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };